reg_app/urls.py
from django.urls import path  
from reg_app import views  


app_name = 'reg_app'
urlpatterns = [
	path('home/', views.home, name='home'),
	path('profile/', views.profile, name='profile'),
	path('signup/', views.signup, name='signup'),
	path('login/', views.login_page, name='login'),
	path('logout/', views.logout_page, name='logout')
]

user_registration/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reg_app.urls'))
]

reg_app/models.py
from django.db import models

# Create your models here.

reg_app/forms.py
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from django import forms  


class NewCreateUserForm(UserCreationForm):
	class Meta:
		model = User 
		fields = ['username', 'email', 'password1', 'password2']

reg_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import NewCreateUserForm


# Create your views here.

def home(request):
	return render(request, 'reg_app/home.html')
@login_required
def profile(request):
	return render(request, 'reg_app/profile.html')

def signup(request):
	form = NewCreateUserForm()
	context = {'form': form}
	if request.method == 'POST':
		form = NewCreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"Hi {username}, you have successfully created an account.")
			return login_page(request)
	else:
		form = NewCreateUserForm()
	return render(request, 'reg_app/signup.html', context)

def login_page(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request, f"Hi {username}, you have successfully logged in.")
			return home(request)

	return render(request, 'reg_app/login_page.html')

def logout_page(request):
	logout(request)
	messages.success(request, f"You have been logged out.")
	return render(request, 'reg_app/logout_page.html')

reg_app/templates/reg_app/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Base Html{% endblock %}</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


</head>
<body>
	{% load crispy_forms_tags %}
	{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="#">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="#">Home</a>
	        <a class="nav-link" href="#">Profile</a>
	        <a class="nav-link" href="#">LogIn</a>
	        <a class="nav-link" href="#">SignUp</a>

    	</div>
	  </div>
	</nav>


	<h1>BASE</h1>
	{% endblock %}

</body>
</html>

reg_app/templates/reg_app/home.html
{% extends 'reg_app/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'reg_app:home' %}">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link active" href="{% url 'reg_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'reg_app:profile' %}">Profile</a>
	        {% if user.is_authenticated %}
				<a class="nav-link" href="{% url 'reg_app:logout' %}">LogOut</a>
			{% else %}
				<a class="nav-link" href="{% url 'reg_app:login' %}">LogIn</a>
	    		<a class="nav-link" href="{% url 'reg_app:signup' %}">SignUp</a>
			{% endif %}
    	</div>
	  </div>
	</nav>



	<div class="container" style="padding-top: 60px">
		<h1>Home</h1>
		<p>Django Registration | Home</p>
		<hr>
	</div>

	<div class="container">
		{% if  messages %}
			{% for message in messages %}
				<div class="alert alert-{{message.tags}}">{{message}}</div>
			{% endfor %}
		{% endif %}
	</div>

	<div class="container" style="position: relative; left:300px">
		<img src="https://1000logos.net/wp-content/uploads/2020/08/Django-Logo-500x313.png">
	</div>
{% endblock %}

reg_app/templates/reg_app/login.html
{% extends 'reg_app/base.html' %}

{% block title %}LogIn{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'reg_app:home' %}">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="{% url 'reg_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'reg_app:profile' %}">Profile</a>
	        <a class="nav-link active" href="{% url 'reg_app:login' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'reg_app:signup' %}">SignUp</a>

    	</div>
	  </div>
	</nav>




	<div class="container" style="padding-top: 60px">
		<h1>LogIn</h1>
		<p>Django Registration | LogIn</p>
		<hr>
	</div>

	<div class="container">
		{% if  messages %}
		{% for message in messages %}
			<div class="alert alert-{{message.tags}}">{{message}}</div>
		{% endfor %}
		{% endif %}
	</div>

	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<div class="container" style="padding-top:50px;">
				<table>
					<tr>
						<div class="row g-3 align-items-center">
							<td>
								<div class="col-auto">
							    	<label for="username" class="col-form-label">Username:</label>
								</div>
							</td>
							<td>
								<div class="col-auto">
							    	<input type="username" id="username" name="username" class="form-control">
								</div>
							</td>
						</div>
					</tr>
					<tr>
						<div class="row g-3 align-items-center">
							<td>
								<div class="col-auto">
							    	<label for="password" class="col-form-label">Password: </label>
								</div>
							</td>
							<td>
								<div class="col-auto">
							    	<input type="password" id="password" name="password" class="form-control">
								</div>
							</td>
						</div>
					</tr>
				</table>
			
			<input class="btn btn-dark" type="submit" value="LogIn" name="submit">
			<p><a href="{% url 'reg_app:signup' %}">Don't have an account?</a></p>
		</form>
		</div>
	</div>
{% endblock %}

reg_app/templates/reg_app/login_page.html
{% extends 'reg_app/base.html' %}

{% block title %}LogIn{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'reg_app:home' %}">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="{% url 'reg_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'reg_app:profile' %}">Profile</a>
	        <a class="nav-link active" href="{% url 'reg_app:login' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'reg_app:signup' %}">SignUp</a>

    	</div>
	  </div>
	</nav>




	<div class="container" style="padding-top: 60px">
		<h1>LogIn</h1>
		<p>Django Registration | LogIn</p>
		<hr>
	</div>

	<div class="container">
		{% if  messages %}
			{% for message in messages %}
				<div class="alert alert-{{message.tags}}">{{message}}</div>
			{% endfor %}
		{% endif %}
	</div>

	<div class="container">
		<form method="POST">
			{% csrf_token %}
			<div class="container" style="padding-top:50px;">
				<table>
					<tr>
						<div class="row g-3 align-items-center">
							<td>
								<div class="col-auto">
							    	<label for="username" class="col-form-label">Username:</label>
								</div>
							</td>
							<td>
								<div class="col-auto">
							    	<input type="username" id="username" name="username" class="form-control">
								</div>
							</td>
						</div>
					</tr>
					<tr>
						<div class="row g-3 align-items-center">
							<td>
								<div class="col-auto">
							    	<label for="password" class="col-form-label">Password: </label>
								</div>
							</td>
							<td>
								<div class="col-auto">
							    	<input type="password" id="password" name="password" class="form-control">
								</div>
							</td>
						</div>
					</tr>
				</table>
			
			<input class="btn btn-dark" type="submit" value="LogIn" name="submit">
			<p><a href="{% url 'reg_app:signup' %}">Don't have an account?</a></p>
		</form>
		</div>
	</div>
{% endblock %}

reg_app/templates/reg_app/logout_page.html
{% extends 'reg_app/base.html' %}

{% block title %}LogIn{% endblock %}

{% block content %}
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'reg_app:home' %}">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="{% url 'reg_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'reg_app:profile' %}">Profile</a>
	        <a class="nav-link active" href="{% url 'reg_app:login' %}">LogIn</a>
	        <a class="nav-link" href="{% url 'reg_app:signup' %}">SignUp</a>

    	</div>
	  </div>
	</nav>




	<div class="container" style="padding-top: 60px">
		<h1>Logged Out</h1>
		<p>Django Registration | LoggedOut</p>
		<hr>
	</div>

	<div class="container">
		{% if  messages %}
			{% for message in messages %}
				<div class="alert alert-{{message.tags}}">{{message}}</div>
			{% endfor %}
		{% endif %}
	</div>


	</div>
{% endblock %}

reg_app/templates/reg_app/profile.html
{% extends 'reg_app/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'reg_app:home' %}">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="{% url 'reg_app:home' %}">Home</a>
	        <a class="nav-link active" href="{% url 'reg_app:profile' %}">Profile</a>
	        {% if user.is_authenticated %}
				<a class="nav-link" href="{% url 'reg_app:logout' %}">LogOut</a>
			{% else %}
				<a class="nav-link" href="{% url 'reg_app:login' %}">LogIn</a>
	    		<a class="nav-link" href="{% url 'reg_app:signup' %}">SignUp</a>
			{% endif %}

    	</div>
	  </div>
	</nav>





	<div class="container" style="padding-top: 60px">
		<h1>Profile</h1>
		<p>Django Registration | Profile</p>
		<hr>
	</div>
	<div class="container">
		<h1>Welcome to User Registration,<br> &emsp; &emsp; &emsp; <strong>{{user.username}}</strong></h1>
	</div>


	
{% endblock %}

reg_app/templates/reg_app/signup.html
{% extends 'reg_app/base.html' %}

{% block title %}SignUp{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="{% url 'reg_app:home' %}">Django Registration</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    
	   	<div class="d-flex navbar-nav" id="navbarNavAltMarkup">
	   		<a class="nav-link" href="{% url 'reg_app:home' %}">Home</a>
	        <a class="nav-link" href="{% url 'reg_app:profile' %}">Profile</a>
	        <a class="nav-link" href="{% url 'reg_app:login' %}">LogIn</a>
	        <a class="nav-link active" href="{% url 'reg_app:signup' %}">SignUp</a>

    	</div>
	  </div>
	</nav>



	<div class="container" style="padding-top: 60px">
		<h1>SignUp</h1>
		<p>Django Registration | SignUp</p>
		<hr>
	</div>
	<div class="container" style="width: 600px; border:solid gray; border-radius: 20px;">
		<form method="POST">
			{% csrf_token %}
			{{form.username|as_crispy_field}}
			{{form.email|as_crispy_field}}
			<div class="row">
				<div class="col-lg-6">
					{{form.password1|as_crispy_field}}
				</div>
				<div class="col-lg-6">
					{{form.password2|as_crispy_field}}
				</div>
			</div>
			
			<input class="btn btn-dark" type="submit" value="SignUp" name="submit">
			<p><a href="{% url 'reg_app:login' %}">Already have an account?</a></p>
		</form>
	</div>
{% endblock %}